[Lockpicking.Timer]
bEnableLockpickTimer = true

[Lockpicking.Settings]
bRemoveLockpickOnTimeout = true
fLockpickingMinTime = 10.0
fLockpickingMaxTime = 50.0
bEnableDynamicLocks = true

[Pickpocket.Timer]
bEnablePickpocketTimer = true

[PickPocket.Settings]
bEnableDynamicPickpocketChance = true
fPickpocketMinTime = 10.0
fPickpocketMaxTime = 50.0

[Reputation.Settings]
iMinItemValueForReputation = 50
iHourlyHeatDecrease = 2
iFenceItemValueHeatThreshold = 158
bShowInfamyMeter = true

[Reputation.Perks]
fShowGoldRushScreenEffect = true
sGoldRushScreenText = "Something catches your eye..."
bEnableGoldRushSound = true
fGoldRushShaderDuration = 60.0

[InfamyMeter.Settings]
bInfamyMeterVertical = false
fInfamyMeterPositionX = 500.0
fInfamyMeterPositionY = 50.0
fInfamyBarLenght = 200.0
fInfamyBarWidth = 20.0

[InfamyMeter.Editor]
fEditorWindowPositionX = 100.0
fEditorWindowPositionY = 400.0

[Keybinds]
sEnterEditMode = "F8"